### ISSUE TITLE
Adding bash install instructions

### ISSUE THREAD

**Issue by seb-mueller** [urbainvaes/fzf-marks#16]
Using bash shell it wasn't obvious on how to get it to work based on current instructions.
I think the readme could benefit from something like along this lines:

```bash
git clone https://github.com/urbainvaes/fzf-marks.git
cd fzf-marks
source fzf-marks.plugin.bash # can be put in  
# make it start up on log:
echo "source $PWD/fzf-marks.plugin.bash" >> ~/.profile
```

Anyway, really nice piece of software!

**Comment by urbainvaes** [comment]
Hi!

Thanks for the suggestion. I agree, it'd be nice to provide more detailed instructions about the installation in bash. I'll add them to the README this weekend.

**Comment by juanMarinero** [comment]
`source $PWD/fzf-marks.plugin.bash` at end of `~/.bashrc` should be not unwarned recommended.

Please change current [README.md](https://github.com/urbainvaes/fzf-marks/blame/master/README.md#L39)
```
# Add a line to ~/.bashrc to load the plugin whenever bash starts in interactive mode
echo "source $PWD/fzf-marks/fzf-marks.plugin.bash" >> ~/.bashrc
```

to something like:

```
# Add next line to ~/.bashrc before loading any not default/builtin aliases/functions
# or if sure no conflicts (like not aliased 'head') just run:
echo "source $PWD/fzf-marks/fzf-marks.plugin.bash" >> ~/.bashrc
```

Maybe is bad practice from me to rename default functions, like:
`alias head='batcat --line-range :10'`

Or maybe the whole repo should change every `head` to `/usr/bin/head` (result of `which head` in Ubuntu); same for `tail`, etc. I doubt that's easy to make it work for several OS and shells, so, I think that at least a warning in the most used shell by beginners (`bash`) would be nice. Thanks!

**Comment by akinomyoga** [comment]
> Maybe is bad practice from me to rename default functions, like:
> ```bash
> alias head='batcat --line-range :10'
> ```

Yeah, I think it's a bad practice to replace the standard utility with a less functional one that doesn't satisfy the POSIX standard...

> Or maybe the whole repo should change every head to /usr/bin/head

We usually simply use `\head`, `\tail`, etc. to suppress alias expansions. But, in this way, `head` cannot be replaced by aliases even when a user wants to intentionally replace `head`.

> ```bash
> # Add a line to ~/.bashrc to load the plugin whenever bash starts in interactive mode
> echo "source $PWD/fzf-marks/fzf-marks.plugin.bash" >> ~/.bashrc
> ```

We may update the comment as you have suggested, but I want to point out that this kind of instruction is quite common for shell plugins. I feel it is easier to expect that the users writing unusual aliases become more careful than to expect that *all* the shell plugins have such common guidance.

**Comment by urbainvaes** [comment]
Many thanks for your suggestion, @juanMarinero.

> We may update the comment as you have suggested, but I want to point out that this kind of instruction is quite common for shell plugins. I feel it is easier to expect that the users writing unusual aliases become more careful than to expect that all the shell plugins have such common guidance.

I agree with @akinomyoga here; the warning you propose applies to many shell plugins besides this one, and I am not sure that repeating the warning in the documentation of every plugin is a good idea.

**Comment by juanMarinero** [comment]
I will do that from now,
> [NOT] replace the standard utility [alias/functions]

I am very thankful for your detailed answers @akinomyoga and @urbainvaes! I learnt something important :)

But since you are not willing to modify the `README` file, I hope other newbies can find current issue-comments if they catch same problem.
