### ISSUE TITLE
Dup marks

### ISSUE THREAD

**Issue by tuyenpm9** [urbainvaes/fzf-marks#21]
Can't reproduce but sometimes plugin give dup mark when trying to use its functions.

**Comment by urbainvaes** [comment]
Thanks, but unfortunately not much I can do without additional information. Could you provide details about the shell you use, the version of the plugin, and possible paste a copy of your marks file?

**Comment by tuyenpm9** [comment]
Thanks, that's latest fzf-marks, manually installed, Z-shell latest, os: archlinux.

I re-map `^g` to `^]` and re-name `~/.fzf-marks` to `~/.marks`, this issue raise with just using only `^]` and `mark` command to create new marks, especially happens when create new map and then select that newly created with `^]` and `enter` to select.

**Comment by noboruma** [comment]
I encountered the exact same issue and I think I have reproduction steps.
create a folder such as "c++" and mark it, such as:
$ mkdir c++ && cd c++ && mark
Then select it (via C-g) and it will be duplicated every time it is accessed.
Maybe it has something to do with the special character '+'?

**Comment by urbainvaes** [comment]
Many thanks for the bug reports. You're right, it had to do with special characters. I have pushed a commit that should fix this.

**Comment by urbainvaes** [comment]
Is the environment `$HOME` variable set, though? By hardcode, you mean you need to `export FZF_MARKS_FILE=...`?

**Comment by tuyenpm9** [comment]
@urbainvaes : It cannot expand variable $HOME somehow, yes I have HOME set:

`touch: cannot touch '$HOME/.marks': No such file or directory`

I had to set it to: ` export FZF_MARKS_FILE='/home/user/.marks'`, I might set a env variable wrong somewhere, Is there any special en var needs to check?

**Comment by urbainvaes** [comment]
Many thanks for your reply. Before using `export FZF_MARKS_FILE='/home/user/.marks'`, what were you using exactly? If you were using `export FZF_MARKS_FILE='$HOME/.marks'`, then the reason it didn't work is the presence of single quotes. If not, then we could use `emulate` to bring back to default zsh. But it would be nice to identify the problem more precisely beforehand ;)

**Comment by noboruma** [comment]
@urbainvaes I can confirm the fix works. Thanks for your hard work & this amazing plugin!

**Comment by urbainvaes** [comment]
@noboruma Thanks for the kind words. :)

**Comment by tuyenpm9** [comment]
@urbainvaes : good catch, think I lost control of my zsh, let fight :)

**Comment by tuyenpm9** [comment]
@urbainvaes : I believe this is symlink problem, when I have `.marks` is a symlink instead of a real-file, fzf-marks fail to locate it.

```
Can't open abc/def/.marks: No such file or directory
```

`~/.marks` is linked to `~/abc/def/.marks`

**Comment by urbainvaes** [comment]
Ah, good catch. Somehow this was fixed for bash but not for zsh. Can you see if it works now?

**Comment by tuyenpm9** [comment]
@urbainvaes : Another issue, my `.marks` is in git repo and then the `touch` command somehow always run when use and select candidate from fzf menu, that trigger git as the file is modified and require me to add to the repo.

**Comment by urbainvaes** [comment]
Thanks. :) That's because the plugin sorts the marks from the least recently to the most recently accessed. https://github.com/urbainvaes/fzf-marks/commit/f5370fe5c836c45801f701b77f36a46179ddd9fd adds the option `FZF_MARKS_KEEP_ORDER`, that you can set to `1` to prevent this from happening.

**Comment by tuyenpm9** [comment]
My favorite plugin ever, thanks.
