### ISSUE TITLE
readlink -f is not portable

### ISSUE THREAD

**Issue by cdlm** [urbainvaes/fzf-marks#22]
The use of `readlink -f` at https://github.com/urbainvaes/fzf-marks/blob/856e875ec4319c6e640b71bec711d2151fbfa757/fzf-marks.plugin.zsh#L65 relies on the GNU implementation and is broken with the BSD `readlink` available by default on macOS, whose man page says:

```
     -f format
             Display information using the specified format.  See the FORMATS section for a description of valid formats.
```

GNU readlink is available but it will probably be named `greadlink` (as installed via Brew)

**Comment by urbainvaes** [comment]
Many thanks for reporting this. Hopefully things should work fine with both relative and absolute symlinks now.

**Comment by cdlm** [comment]
hmm… unfortunately it's still not jumping anywhere 🙁
I don't think I have symlinks in the bookmarks I tried, so I suspect there is another problem. Must be a recent change though, since I update many tools quasi-daily…

**Comment by urbainvaes** [comment]
Thank you. Hmm, that is strange. Are there any special characters in your bookmarks/directories that could be the cause? And is there an error message? I'd be happy to look into it, but at this point I have no idea what the cause could be.

**Comment by cdlm** [comment]
Nothing funny with my paths, I believe. I’ll investigate later tonight or tomorrow, when I get a chance.

**Comment by urbainvaes** [comment]
Thank you very much, and sorry for the inconvenience.

**Comment by cdlm** [comment]
It seems that the `\?` in the sed call at 382e990cdc8778ceb31f4b7c49834ae5515a881f doesn't work. I'm guessing it's for matching a space before the colon, but that's not really needed in that case. I tried a couple variants, and got a fix by matching the bookmark name and colon with `[^:]*:`. That would be a problem if colons are allowed in bookmark names, though, but there should be some sanitizing of the inputs anyway. Rewriting into modern regular expressions with `sed -E` would work with BSD sed as well.

Also in that line, the `-n` flag to sed and the `/p` substitution flag seem to be contradictory, but maybe I'm missing a corner case… could you explain?

**Comment by urbainvaes** [comment]
Thank you very much for tracking down the error! The `\?` was added in the bash version of the script in the pull request https://github.com/urbainvaes/fzf-marks/pull/20. But you're right, and using `.* \?` was equivalent to using just `.*` anyway.

About the `-n` flag, I don't remember why I wrote it like this originally. It doesn't make much sense to me either now; I'll fix it straight away.

**Comment by urbainvaes** [comment]
I have changed the regex for the bookmark and colon and space to `.*: `. This way, bookmarks can contain spaces. The downside is that it leads to problems when the directory contains the sequence `: `. In fact, the best regular expression would probably be `.* : `, given that plugin adds ` : ` between the bookmark and the directory when `mark` is used, but I know from a previous pull request that some people use marks file that start with `: `, with no leading space.
