### ISSUE TITLE
Fish shell plugin is currently broken

### ISSUE THREAD

**Issue by snowe2010** [urbainvaes/fzf-marks#31]
```
❯ fish -v
fish, version 3.1.0
```

```
❯ ~/.config/fish/functions/fzf-marks.plugin.fish (line 1): Invalid redirection target:
_color_marks < $FZF_MARKS_FILE | $FZF_MARKS_COMMAND \
             ^
in command substitution
        called on line 93 of file ~/.config/fish/functions/fzf-marks.plugin.fish
in function 'fzm'
~/.config/fish/functions/fzf-marks.plugin.fish: Unknown error while evaluating command substitution
```

**Comment by snowe2010** [comment]
Actually this appears to happen due to fisher installing from the root directory. This can probably be fixed by moving the fish file to `conf.d`

**Comment by urbainvaes** [comment]
Thanks for reporting the issue. I'm not very familiar with `fish`, but it seems to me that adding an `eval` fixed the problem? Could you check?

The issue as I understand was that:
```
set a 'fzf --ansi'
$a
```
does not work in `fish`.

**Comment by snowe2010** [comment]
Sorry, I have been pretty busy. That appears to get rid of the error, but now I get a different error: 

```
❯ fish: Unknown command: fzm
```

**Comment by snowe2010** [comment]
Oh that was because it's still not in conf.d. adding `eval` results in the error 

> unknown option: ctrl-t:toggle,

**Comment by urbainvaes** [comment]
No worry. Could you explain what you mean with `conf.d`, I'm not familiar with how plugins work in `fish`. Have you tried including `source ~/PATH_TO_fzf-marks.plugin.fish` in `~/.config/fish/config.fish`. Also, what version of `fish` are you using?

**Comment by raw-bin** [comment]
Hi @urbainvaes, @snowe2010. I faced the same issues. Please see the MR at https://github.com/urbainvaes/fzf-marks/pull/32 which seem to fix the problems for me. @snowe2010 if you could confirm, that would be awesome!

@urbainvaes : Thanks for a great tool! :)

**Comment by snowe2010** [comment]
So I'm using [fisher](https://github.com/jorgebucaran/fisher) which expects anything that is in the root to get installed to the `functions` directory and anything in `conf.d` gets installed to the conf.d directory. Since the `fzf-marks.plugin.fish` file is in the root, it gets installed in the `functions` directory, leading to it not working. Moving it to `conf.d` like my fork does causes it to work just fine. 

Sorry if I've been confusing, switching back and forth between projects has got me all mixed up. I don't know if you want to provide this fix, since it seems you might want it in the root, but just an fyi, that it doesn't work with fisher in the current config.

**Comment by raw-bin** [comment]
Just to be clear: Are you saying that moving fzf-marks.plugin.fish to conf.d causes things to work _without_ my fix ?

**Comment by urbainvaes** [comment]
Thanks both for your input. @raw-bin I have merged your pull request, many thanks for finding a fix. Did you understand why adding `-g` fixed the issue? On my computer, it seems that the variables becomes part of the environment with or without it.

@snowe2010 , I added the plugin in `conf.d` as a symbolic link https://github.com/urbainvaes/fzf-marks/commit/6e2df353e93ed833c3af11b765c9b0c07fc661cb, for backward compatibility. Do that look like a good solution to you?

**Comment by raw-bin** [comment]
Hi.

Thanks for merging!

On my machine (macos Catalina) global declarations for fish only work if
'-g' is used. Looking at the fish documentation, it does make sense that
global vars need to be explicitly declared first.

The only explanation I have for your observation is that the fish
documentation states that if there were _any_ variables already in the
environment from where fish was launched, then they are imported into the
new fish instance as global variables. Is fish your login shell ? I'm
guessing not ? If that is true (that it's not your login shell) then
perhaps there's something in the 'parent' shell that had declared these
vars before fish launched and that's why they got imported into fish's
global scope ?

In my case, fish is the login shell and maybe that's why it had a 'clean'
environment to start off with. Hence the need for explicit declarations ?

**Comment by urbainvaes** [comment]
Ah, that explains it! My login shell is `zsh`, so the environment was just inherited by `fish`. Many thanks! :)

**Comment by snowe2010** [comment]
@raw-bin yes, I didn't need your fix, just moved it to conf.d.

@urbainvaes that is perfectly fine! I wasn't sure if fish would pick up the symbolic link. 

I was also having weird issues because I was trying to switch from zsh to fish. Seems this ticket can be closed then!

**Comment by snowe2010** [comment]
closed by https://github.com/urbainvaes/fzf-marks/commit/6e2df353e93ed833c3af11b765c9b0c07fc661cb
