### ISSUE TITLE
front end to fzm

### ISSUE THREAD

**Issue by nkh** [urbainvaes/fzf-marks#34]
Hi, thanks for fzf-marks, I use it all the time.

I have wrapped it up in something that makes it more practical for me and maybe makes it more practical for other.

Let me know if something isn't clear.

cdm ()
{
if [[ ${#@} == 0 || ${#@} -gt 1 ]] ; then
	fzm
else
	matches=$(cat $FZF_MARKS_FILE | awk '{print $1}' | grep "$1" | wc -l) 

	if [[ $matches == 0 ]] ; then
		fzm
	elif [[ $matches -gt 1 ]] ; then
		directory=$(_color_marks <<< $(perl -ane '$F[0] =~ /'$1'/ and print $_' $FZF_MARKS_FILE) | fzf --ansi --height 50% --reverse) 
		[[ $? == 0 ]] && cd $(echo "$directory" | awk '{print $3}')
	else
		directory=$(perl -ane '$F[0] =~ /'$1'/ and print $F[2]' $FZF_MARKS_FILE) 
		[[ -n "directory" ]] && cd "$directory" || fzm "$1"
	fi
fi
}

_cdm_completion()
{
COMPREPLY=( $( compgen -W "$(cat $FZF_MARKS_FILE | awk '{print $1}' | ([[ -n $2 ]] && grep $2 || cat | tr '
' ' '))" -- ${COMP_WORDS[$COMP_CWORD]} ))
}

**Comment by urbainvaes** [comment]
Hi, and many thanks for the suggestions?

Could you perhaps describe briefly in words what these functions do?

If I understand properly, `cdm` enables to

- Change directory directly if there is only one match;

- Call `fzf ` on a filtered list if there is more than one list.

Is there anything else? For the first item, I would suggest just including `-1` in the `fzf` command, which does precisely what the item describes. For example,
```
FZF_MARKS_COMMAND='fzf --height 40% --reverse -e -1
```
For the second item, I think this is the default behavior of `fzm` already, isn't it?

Regarding the completion, I didn't manage to get it working (should I just copypaste in my `.zshrc`?), but I assume this is to have completion after `fzm`? If yes, I think this would be a good idea, and I will play around with this.

**Comment by urbainvaes** [comment]
For `zsh`, these two lines seem to work quite well for basic completetions:
```
marks=$(cat ~/.fzf-marks | sed 's/\(.*\) : .*$/\1/')
compctl -k "(${marks})" -M 'm:{a-z}={A-Z}' fzm
```

**Comment by nkh** [comment]
hi,
given

a : path
a2: path
b2: path

cdm <tab>,  give the "a a2 b2" completions
cdm a<tab>, give the "a a2" completions 
cdm b + return, goes to b2's directory
cdm a + return, opens fzm with only a entries (IE, a doesn't match anything in the paths)
cdm any_string + return, opens fzm and pass it any_string
cdm + return, opens fzm

 I have no idea how things work in zsh and the two lines above may do everything cdm does.

#1 as for adding -1 to fzf, cdm searches only the tags not the paths, I believe that would be different
#2 cdm only handles tags, maybe I'm not using fzm properly

the completion is for cdm (that would have been clearer if I didn't forget the complete line :) )

**Comment by urbainvaes** [comment]
Hi,

Many thanks for the explanation; I understand better your suggestion now.

Might it be that your desired behavior, in the case where `enter` is pressed, is approximated by something like this?
```
FZF_MARKS_COMMAND='fzf --height 40% --reverse -e -1 -n 1 -d " : "'
```

Regarding completion, I am wondering whether it might be easier to just use `complete -W`, and to update the list of words when a mark is added or deleted. Something like
```
function setup_completion {
    complete -W "$(sed 's/\(.*\) : .*$/"\1"/' < "$FZF_MARKS_FILE")" fzm
}

setup_completion
```
What do you think?

**Comment by urbainvaes** [comment]
I think this is more or less resolved with the new completion, so I'll close this issue, but feel free to reopen it if you are not satisfied with the changes or have other suggestions.

Many thanks again!
