### ISSUE TITLE
fzf-marks.plugin.zsh:177 command not found: compdef

### ISSUE THREAD

**Issue by qaraluch** [urbainvaes/fzf-marks#36]
Seems that after last month update I keep getting: :scream: :see_no_evil: 
```
~/.cache/zsh/plugs/fzf-marks/fzf-marks.plugin.zsh:177: command not found: compdef
```
https://github.com/urbainvaes/fzf-marks/blob/19c526a521ca231a8396362614979b6af2ad6262/fzf-marks.plugin.zsh#L177

I do not really know what is going on because I've got zsh's completion system activated in my zshrc file:
```
autoload -Uz compinit
compinit
```
and after spawning shell the `compdef` command is available?

btw. I appreciate your work! thx :green_heart:

**Comment by urbainvaes** [comment]
Hi! 

Many thanks for reporting the issue!

Just to be sure, do you activate completion before sourcing the plugin?

**Comment by qaraluch** [comment]
Yep.  That is the solution. Before plugin sourcing you need to init  zsh's completion system like that:
```
autoload -Uz compinit
compinit 
source ~/fzf-marks/fzf-marks.plugin.zsh
```
thank you!

**Comment by urbainvaes** [comment]
Thanks again for reporting this issue! I added a check, before calling `compdef` in the plugin code, that completion is enabled.
