### ISSUE TITLE
Use case with tmux - add new window based on marks

### ISSUE THREAD

**Issue by qaraluch** [urbainvaes/fzf-marks#37]
I'd like share with you guys little script that I use on a daily basis. It spawns new tmux's window based on mark entries. I hope someone find this useful. :eyes: :pray: :tada:

```bash
#!/usr/bin/env bash
# Author: qaraluch - 07.2020 - MIT
# Add new window to the tmux session
# based on fzf-marks entries
readonly _pName=$(basename $0)
IFS=$'\n' readonly fzfMarksEntry=("$(cat ${FZF_MARKS_FILE} | fzf-tmux --exit-0)")
readonly name=$(awk -F':' '{print $1}' <<< "$fzfMarksEntry" | sed 's/[ \t]\?//g')
readonly path=$(awk -F':' '{print $2}' <<< "$fzfMarksEntry" | sed 's/[ \t]\?//g')
if [[ -d "$path" ]]; then
  tmux new-window -d -n "${name}" -c "${path}"
else
  echo "[ ${_pName} ] Destination dir for new tmux window seems does not exist... :o"
fi
```

**Comment by urbainvaes** [comment]
Hi!

Thank you very much for this! Since the script might be useful to other people, I have copied it to the wiki page for the plugin, where it will hopefully be more visible than in this issue.

Feel free to amend / improve the wiki page if you are not satisfied with my description.
