### ISSUE TITLE
(feature request) Inserting marked directory in cmd rather than jump to it

### ISSUE THREAD

**Issue by seb-mueller** [urbainvaes/fzf-marks#40]
First of all, thanks again for fzm, using it daily! 

One thing that could be a nice improvement is placing a selected dir into the command line rather than jumping to it.
I.e. say just want to list the content of a marked dir, being on the shell, typying `ls` hitting ctrl-G to fire up fzm, 
I could imagine there to be an additional option to just copy the marked dir to the shell. Ending up in `ls myselecteddir` on the cmd.

I could have look to implement it myself if you don't have time etc, but would have to get proficient first.

Naivly, I'd imagine to create a new function similar to the jump function, but instead of cd pasting the dir on the cmd:

https://github.com/urbainvaes/fzf-marks/blob/6a116efcff046e47b62edd90df48111302731e81/fzf-marks.plugin.zsh#L129

I.e. instead of `cd` using `echo`, which doesn't quite work, but I wouldn't know to make it work, maybe I'm just missing the right command..

**Comment by urbainvaes** [comment]
This should now be possible in zsh. Many thanks to you for the suggestion, and many thanks to @3ximus for the implementation!

**Comment by seb-mueller** [comment]
Brilliant, just tried it with zsh and it works like a charm! Thanks so much @3ximus and @urbainvaes ! I consider this a game-change in my cmd workflow, since I often need to copy inot or ls a few important directories all the time!
