### ISSUE TITLE
[Feature Request] Move to the next line item automatically on ctrl-t(toggle)

### ISSUE THREAD

**Issue by cibinmathew** [urbainvaes/fzf-marks#52]
It would be more useful to move to the next line on selection.
FZF uses toggle+down by default on toggling a selection which is bound to `tab` key. This is what user would do most of the time as well.

**Comment by cibinmathew** [comment]
@urbainvaes do you think this makes sense to replace the current behaviour. I can work on a PR in that case.

**Comment by urbainvaes** [comment]
Hi @cibinmathew,

Many thanks for the suggestion.

Yes, I think it would make sense to align the behavior of the `ctrl-t` with that of `Tab`.

**Comment by cibinmathew** [comment]
ok. I will create a PR shortly.

**Comment by urbainvaes** [comment]
Many thanks!
