### ISSUE TITLE
cd hooks aren't triggered after jumping

### ISSUE THREAD

**Issue by aaronjensen** [urbainvaes/fzf-marks#6]
For example, if you use [direnv](https://github.com/direnv/direnv) you have to hit enter once on the empty prompt before it catches that you changed directory. I'm not sure if I've got something wrong in my setup or if this is just a side effect of how fzf-marks actually changes directories...

**Comment by urbainvaes** [comment]
Thank you for reporting this issue. I notice that the same problem happens when using the default Alt-c keybinding defined by fzf - somehow the change of directory is not registered by direnv. I don't know zsh very well, so I don't know how to fix the problem yet, but will look into it.

**Comment by spetex** [comment]
I just encountered similar problem when jumping into directory with autoenv it spits out awk i/o error but it actually proceeds with the hooks in .env or .autoenv.zsh files.
